# -*- coding: utf-8 -*-
"""which_nodes_did_I_hear.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Zp-Ugd6QYCiocSOwNB6_dRvtOCTWt12H

## Check which nodes were heard during the test

Visualize data from SMesh Build v1.0 nodes, data gathered on 11/06/24 in Lab64

Authors: Daniel Neamati and Lisa Fung

Last Updated: 11/06/2024
"""

# Mount Google Drive to import data
# Do this first since it will prompt authentication
from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

folderpath = '/content/drive/Shared drives/SMesh: Sustainability Radio Sensor Networks/smesh-software/Data Visualization/pre_pepperwood_mesh_test_2024_11_06/'
data = {}
logger = "0ff4"
# sensor_types = ["device_metrics", "bme688", "ina260", "pmsa003i"]

base_vars = ['datetime', 'from_node']
net_vars = ['rxSnr', 'hopLimit', 'rxRssi', 'hopStart']

sensor_headers = {
    "device_metrics": ['batteryLevel', 'voltage', 'channelUtilization', 'airUtilTx'],
    "bme688": ['temperature', 'relativeHumidity', 'barometricPressure', 'gasResistance', 'iaq'],
    "ina260": ['ch3Voltage', 'ch3Current'],
    "pmsa003i": ['pm10Standard', 'pm25Standard', 'pm100Standard', 'pm10Environmental', 'pm25Environmental', 'pm100Environmental']
}
sensor_types = sensor_headers.keys()

for sensor in sensor_types:
    sensor_headers[sensor] = base_vars + sensor_headers[sensor] + net_vars

for sensor in sensor_types:
    print(sensor + " started")
    data[sensor] = pd.read_csv(folderpath + logger + "_" + sensor + ".csv",
                               header=None, parse_dates=[0])
    data[sensor].columns = sensor_headers[sensor]
    data[sensor]['from_short_name'] = data[sensor]['from_node'].str[-4:]

    # print(data[sensor].dtypes)
    # print(data[sensor].head())

    print(sensor + " completed")

col_id = 'from_short_name'

for sensor in sensor_types:
    print("-----\n" + sensor + " started")
    unique_ids = data[sensor][col_id].unique()
    print("sorted:", np.sort(unique_ids), "\n")

    # Sort false will mean it sorts by dataframe column rather than frequency
    unique_stats = data[sensor][col_id].value_counts(sort=True)
    print(unique_stats)

    print(sensor + " completed\n-----\n")

# data["ina260"][data["ina260"][data["ina260"].columns[1]] == "0x433abf20"]
data["ina260"][data["ina260"]["from_short_name"] == "bf20"]

fig, axes = plt.subplots(nrows=1, ncols=2,
                         figsize=(12, 4))

# 'channelUtilization', 'airUtilTx'
data["device_metrics"]['channelUtilization'].hist(ax=axes[0])
axes[0].set(xlabel="Channel Utilization [%]", ylabel="Frequency")

data["device_metrics"]['airUtilTx'].hist(ax=axes[1])
axes[1].set(xlabel="Air Utilization Tx [%]", ylabel="Frequency");

fig, axes = plt.subplots(nrows=1, ncols=2,
                         figsize=(12, 4))

data["device_metrics"].plot.scatter(x='datetime', y='channelUtilization', ax=axes[0], rot=45)
data["device_metrics"].plot.scatter(x='datetime', y='airUtilTx', ax=axes[1], rot=45);

data["device_metrics"].dtypes

for sensor in sensor_types:
    df_from_node_sorted = data[sensor].sort_values(by='from_short_name')
    ax_heard = df_from_node_sorted.plot.scatter(x='datetime', y='from_short_name', rot=45)
    ax_heard.set_title(sensor)
    plt.show()